apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: petshop-web
  namespace: petshop
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  rules:
  - host: petshop.sixeyed.com
    http:
      paths:
      - path: /
        backend:
          serviceName: petshop-web
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: petshop-web-static
  namespace: petshop
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "on" 
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache static-cache;
      proxy_cache_valid 60m;
      add_header X-Cache $upstream_cache_status;
spec:  
  rules:
  - host: petshop.sixeyed.com
    http:
      paths:
      - path: /Prod_Images/
        backend:
          serviceName: petshop-web
          servicePort: 80
      - path: /Comm_Images/
        backend:
          serviceName: petshop-web
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: petshop-webservice
  namespace: petshop
spec:
  rules:
  - host: ws.petshop.sixeyed.com
    http:
      paths:
      - path: /
        backend:
          serviceName: petshop-webservice
          servicePort: 80