apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-np
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30000
    - name: https
      port: 8040
      targetPort: https
      nodePort: 30040
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller