apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
        app: widgetario
        component: web
  template:
    metadata:
      labels: 
        app: widgetario
        component: web
    spec:
      containers:
        - name: app
          image: widgetario/web:21.03
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: web-features
          volumeMounts:
            - name: api-config
              mountPath: "/app/secrets"
              readOnly: true
      volumes:
        - name: api-config
          secret:
            secretName: web-api