# v4 uses asynchronous messaging with NATS
version: "3.7"

services:
  signup-db:
    image: dak4dotnet/sql-server:2017
    environment:
      - sa_password=DockerCon!!!
    networks:
      - app-net

  signup-web:
    image: dak4dotnet/signup-web:v2
    environment:
      - Dependencies:IProspectSaveHandler=SignUp.Web.ProspectSave.AsynchronousProspectSaveHandler
    labels:
      - "traefik.frontend.rule=PathPrefix:/app"
      - "traefik.frontend.priority=30"
    depends_on:
      - signup-db
    networks:
      - app-net

  homepage:
    image: dak4dotnet/homepage
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=10"
    networks:
      - app-net

  proxy:
    image: traefik:v1.7.18-windowsservercore-1809
    command: --docker --docker.endpoint=npipe:////./pipe/docker_engine --docker.watch --api
    ports:
      - "8040:80"
      - "8080:8080"
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine
    networks:
      - app-net

  message-queue:
    image: nats:2.1.0-nanoserver-1809
    networks:
      - app-net

  signup-save-handler:
    image: dak4dotnet/save-handler
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat
