version: '3.2'

services:

  signup-db:
    image: dockersamples/mta-dev-signup-db:v1
    networks:
      - app-net

  message-queue:
    image: nats:1.0.4-nanoserver
    networks:
      - app-net

  signup-app:
    image: dockersamples/mta-dev-signup-app:v4
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  signup-save-handler:
    image: dockersamples/mta-dev-signup-save-handler:v1
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  signup-index-handler:
    image: dockersamples/mta-dev-signup-index-handler:v1
    depends_on:
      - message-queue
      - elasticsearch
    networks:
      - app-net

  elasticsearch:
    image: dockersamples/elasticsearch:5.6.0-nanoserver
    networks:
      - app-net

  kibana:
    image: dockersamples/kibana:5.6.0-windowsservercore
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat